name: CIPago
on:
  push:
    branches: [pagoz]

jobs:
  genpago:
    runs-on: ubuntu-latest
    
    steps:
        - name: branch
          uses: actions/checkout@v2
          # with:
          #   BRANCH: pagoz
          
        - name: see branch
          run: git branch

        - name: install
          run: npm install
          
        - name: build
          run: npm run build

#         - name: upnow to master
#           run: |
#             cd pago
#             ls
            
        - name: deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{secrets.CICDz}}
            BRANCH: master
            FOLDER: pago
