name: genSitePage
on:
  push:
    branches: [vpg]

jobs:
  GenPage:
    runs-on: ubuntu-latest

    steps:
      - name: Salutu
        run: echo 'Say hello~'

      - name: Tiri 1
        uses: actions/checkout@v2
        with:
          BRANCH: vpg

      - name: Tiri 2
        run: git branch

      - name: Instali
        run: npm install
        run: ls
      
      - name: Kompili
        run: npm run build

      - name: Pusi
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          ACCESS_TOKEN: ${{secrets.GSP}}
          BRANCH: master
          FOLDER: pago
