name: genSitePage
on:
  push:
    # 切换分支。
    branches: [vpg]
# 计划1（生成vue page 并 提交到 mastar）。
jobs:
  GenPage:
    runs-on: ubuntu-latest

    steps:
      - name: Salutu
        run: echo 'Say hello~'

      - name: Tiri 1
        uses: actions/checkout@v2
        # with:
        #   BRANCH: vpg

      - name: Tiri 2
        run: git branch

      - name: Tiri 3
        run: ls

      - name: Instali
        run: npm install

      - name: Kompili
        run: npm run build

      - name: Pusi
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          ACCESS_TOKEN: ${{secrets.GSP}}
          BRANCH: master
          FOLDER: www
